/* Display data for the basket. Prices here are for showing a running
   total only — the amount charged is always resolved server-side from
   Stripe in /api/checkout. */
window.WORKS = {
  "succulent-garden":       { t: "Succulent Garden",            p: 850000, m: "Oil on canvas", d: "71 × 71 cm" },
  "harbour-at-rest":        { t: "Harbour at Rest",             p: 720000, m: "Oil on canvas", d: "70.5 × 50.5 cm" },
  "wide-blue-bay":          { t: "Wide Blue Bay",               p: 640000, m: "Oil on canvas", d: "75 × 38 cm" },
  "paris-in-bloom":         { t: "Paris in Bloom",              p: 570000, m: "Oil on canvas", d: "75 × 30 cm" },
  "emerald-surf":           { t: "Emerald Surf",                p: 530000, m: "Oil on canvas", d: "60 × 33 cm" },
  "lavender-abbey":         { t: "Lavender Abbey",              p: 490000, m: "Oil on canvas", d: "41 × 41 cm" },
  "the-curl":               { t: "The Curl",                    p: 480000, m: "Oil on canvas", d: "46 × 34 cm" },
  "muizenberg-beach-huts":  { t: "Beach Huts",                  p: 470000, m: "Oil on canvas", d: "50 × 30 cm" },
  "beached":                { t: "Beached",                     p: 420000, m: "Oil on canvas", d: "30 × 40 cm" },
  "turquoise-break":        { t: "Turquoise Break",             p: 420000, m: "Oil on canvas", d: "45 × 27 cm" },
  "glass-wave":             { t: "Glass Wave",                  p: 420000, m: "Oil on canvas", d: "45 × 27 cm" },
  "hydrangeas":             { t: "Hydrangeas in Bloom",         p: 420000, m: "Oil on canvas", d: "40.5 × 30 cm" },
  "spring-blossom":         { t: "Spring Blossom",              p: 390000, m: "Oil on canvas", d: "32 × 32 cm" },
  "blossom-walk":           { t: "Blossom Walk",                p: 360000, m: "Oil on canvas", d: "30 × 30 cm" },
  "proteas-in-the-dark":    { t: "Proteas in the Dark",         p: 300000, m: "Oil on canvas", d: "24.5 × 25.5 cm" },
  "red-boats":              { t: "Red Boats, Clear Water",      p: 295000, m: "Oil on canvas", d: "20 × 30 cm" },
  "pink-protea":            { t: "Pink Protea",                 p: 270000, m: "Oil on canvas", d: "25 × 20 cm" },
  "king-protea":            { t: "King Protea",                 p: 270000, m: "Oil on canvas", d: "25 × 20 cm" },
  "little-donkey":          { t: "Little Donkey",               p: 200000, m: "Oil on canvas", d: "14.5 × 18.5 cm" },
  "provence-lavender-farm": { t: "Provence Lavender Farm",      p: 300000, m: "Oil on board",  d: "61 × 46 cm" },
  "red-roofs-still-water":  { t: "Dullstroom",      p: 225000, m: "Oil on board",  d: "43.5 × 35 cm" },
  "clifftop-cottage":       { t: "Clifftop Cottage",            p: 205000, m: "Oil on board",  d: "40 × 30 cm" },
  "cosmos-and-windpump":    { t: "Cosmos and Windpump",         p: 205000, m: "Oil on board",  d: "40 × 30 cm" },
  "the-sea-arch":           { t: "The Sea Arch",                p: 205000, m: "Oil on board",  d: "40 × 30 cm" },
  "nguni-on-the-shore":     { t: "Nguni on the Shore",          p: 175000, m: "Oil on board",  d: "35 × 25 cm" },
  "storm-light":            { t: "Storm Light",                 p: 175000, m: "Oil on board",  d: "35 × 25 cm" },
  "table-mountain-bay":     { t: "Table Mountain from the Bay", p: 135000, m: "Oil on board",  d: "30.5 × 15 cm" },
  "winelands-cottage":      { t: "Winelands Cottage",           p: 120000, m: "Oil on board",  d: "20 × 17.5 cm" },
  "table-mountain-sunset":  { t: "Table Mountain at Sunset",    p: 120000, m: "Oil on board",  d: "20 × 18 cm" },
  "geraniums-on-the-steps": { t: "Geraniums on the Steps",      p: 100000, m: "Oil on board",  d: "16 × 14.5 cm" },
  "lighthouse-on-the-rock": { t: "Lighthouse on the Rock", p: 470000, m: "Oil on canvas", d: "30 × 50 cm" },
  "lighthouse": { t: "Lighthouse", p: 470000, m: "Oil on canvas", d: "30 × 50 cm" },
  "bushveld-acacias": { t: "Bushveld Acacias", p: 430000, m: "Oil on canvas", d: "42 × 30 cm" },
  "sandy-beach": { t: "Sandy Beach", p: 420000, m: "Oil on canvas", d: "30 × 40.5 cm" },
  "country-dawn": { t: "Country Dawn", p: 320000, m: "Oil on canvas", d: "24 × 30 cm" },
  "choppy-seas": { t: "Choppy Seas", p: 270000, m: "Acrylic on canvas", d: "20 × 25 cm" },
  "west-coast-bay": { t: "West Coast Bay", p: 255000, m: "Oil on board", d: "50 × 40 cm" },
  "cape-cottage-on-the-beach": { t: "Cape Cottage on the Beach", p: 205000, m: "Oil on board", d: "40.5 × 30.5 cm" },
  "forest-stream": { t: "Forest Stream", p: 205000, m: "Oil on board", d: "30 × 40 cm" },
  "forest-stream-2": { t: "Forest Stream 2", p: 205000, m: "Oil on board", d: "40 × 30 cm" },
  "through-the-garden-gate": { t: "Through the Garden Gate", p: 175000, m: "Oil on board", d: "25 × 35.5 cm" },
};
