// Slug → Stripe price/product. Server-side only: the browser sends slugs,
// never amounts, so the basket cannot be tampered with to change a price.
// Amounts here are pence and must match the Stripe price objects.
export const PRICES = {
  "succulent-garden":       { price: "price_1TxicABrZ8ulnngRG9QheR9r", product: "prod_UxdtYtPkJad7ou", amount: 850000, name: "Succulent Garden" },
  "harbour-at-rest":        { price: "price_1TxicvBrZ8ulnngRy6vvKMe2", product: "prod_UxduQsSu1EzuJB", amount: 720000, name: "Harbour at Rest" },
  "wide-blue-bay":          { price: "price_1Txid7BrZ8ulnngRE5vkUBvN", product: "prod_Uxdu3ufvAgDJUV", amount: 640000, name: "Wide Blue Bay" },
  "paris-in-bloom":         { price: "price_1TxidIBrZ8ulnngROKeW0uW4", product: "prod_Uxdv5OYwJpVlyw", amount: 570000, name: "Paris in Bloom" },
  "emerald-surf":           { price: "price_1TxidVBrZ8ulnngRl3IpaaMp", product: "prod_UxdvjeHQsTnl8R", amount: 530000, name: "Emerald Surf" },
  "lavender-abbey":         { price: "price_1TxidjBrZ8ulnngR8ppFngZM", product: "prod_Uxdvs1oW5UgNHq", amount: 490000, name: "Lavender Abbey" },
  "the-curl":               { price: "price_1TxidvBrZ8ulnngRKOrLabMO", product: "prod_Uxdvf03KzW2Jhn", amount: 480000, name: "The Curl" },
  "muizenberg-beach-huts":  { price: "price_1Txie9BrZ8ulnngRTqCl3Ieh", product: "prod_UxdwvPchKiSTmN", amount: 470000, name: "Beach Huts" },
  "beached":                { price: "price_1TxieOBrZ8ulnngRhTOeUsDR", product: "prod_UxdwbQdOcroqPS", amount: 420000, name: "Beached" },
  "turquoise-break":        { price: "price_1TxiewBrZ8ulnngRXSz77xX8", product: "prod_UxdwLWwCvhudHV", amount: 420000, name: "Turquoise Break" },
  "glass-wave":             { price: "price_1Txif7BrZ8ulnngRuZXTFiS0", product: "prod_Uxdx2CtygXBe8B", amount: 420000, name: "Glass Wave" },
  "hydrangeas":             { price: "price_1TxifNBrZ8ulnngRoZuTQF9y", product: "prod_UxdxNPrl9Y8EDH", amount: 420000, name: "Hydrangeas in Bloom" },
  "spring-blossom":         { price: "price_1TxifXBrZ8ulnngRTYkuVXbj", product: "prod_UxdxECVK5VHfzL", amount: 390000, name: "Spring Blossom" },
  "blossom-walk":           { price: "price_1Txig0BrZ8ulnngR5avFgld8", product: "prod_UxdxM19bDwf3z3", amount: 360000, name: "Blossom Walk" },
  "proteas-in-the-dark":    { price: "price_1TxigDBrZ8ulnngRry6qV4w8", product: "prod_Uxdysg2jZIJV49", amount: 300000, name: "Proteas in the Dark" },
  "red-boats":              { price: "price_1TxigPBrZ8ulnngRCRUNkvae", product: "prod_UxdyiT0IO4VEn5", amount: 295000, name: "Red Boats, Clear Water" },
  "pink-protea":            { price: "price_1TxigdBrZ8ulnngRSHxSqXY1", product: "prod_UxdyvI5VKRGaYm", amount: 270000, name: "Pink Protea" },
  "king-protea":            { price: "price_1TxignBrZ8ulnngRXvnXdqkS", product: "prod_UxdyQeURSKOlq4", amount: 270000, name: "King Protea" },
  "little-donkey":          { price: "price_1TxigyBrZ8ulnngRm34ucGOL", product: "prod_UxdyABJGc1JWlI", amount: 200000, name: "Little Donkey" },
  "provence-lavender-farm": { price: "price_1TxiciBrZ8ulnngRbE3a1RYy", product: "prod_UxdufHZiBl2tZ4", amount: 300000, name: "Provence Lavender Farm" },
  "red-roofs-still-water":  { price: "price_1TxihBBrZ8ulnngRIF7yPMM8", product: "prod_UxdzAeQpAbqBH2", amount: 225000, name: "Red Roofs, Still Water" },
  "clifftop-cottage":       { price: "price_1TxihLBrZ8ulnngR7twjrcFy", product: "prod_UxdzuNZkqascyx", amount: 205000, name: "Clifftop Cottage" },
  "cosmos-and-windpump":    { price: "price_1TxihWBrZ8ulnngRq8T9yCI8", product: "prod_UxdzIamb4O4Wq6", amount: 205000, name: "Cosmos and Windpump" },
  "the-sea-arch":           { price: "price_1TxihgBrZ8ulnngRyZgNyZuT", product: "prod_Uxdzak9BPyD5Tl", amount: 205000, name: "The Sea Arch" },
  "nguni-on-the-shore":     { price: "price_1TxihrBrZ8ulnngRz1xbv1Ka", product: "prod_UxdzgvnHSTPsBT", amount: 175000, name: "Nguni on the Shore" },
  "storm-light":            { price: "price_1Txii2BrZ8ulnngRu8dgBUtS", product: "prod_Uxe0HjSDVKlFKn", amount: 175000, name: "Storm Light" },
  "table-mountain-bay":     { price: "price_1TxiiFBrZ8ulnngRXkZmn4fE", product: "prod_Uxe0QmY8RTlBTF", amount: 135000, name: "Table Mountain from the Bay" },
  "winelands-cottage":      { price: "price_1TxiiPBrZ8ulnngRCumwvWbg", product: "prod_Uxe0uaZFfZqaOg", amount: 120000, name: "Winelands Cottage" },
  "table-mountain-sunset":  { price: "price_1TxiieBrZ8ulnngRe2dkFx7x", product: "prod_Uxe0E019TzPlcK", amount: 120000, name: "Table Mountain at Sunset" },
  "geraniums-on-the-steps": { price: "price_1TxiipBrZ8ulnngRVs3kxlIA", product: "prod_Uxe05MMeJKMCKl", amount: 100000, name: "Geraniums on the Steps" },
};
